allowBuilds:
  '@firebase/util': set this to true or false
  '@parcel/watcher': set this to true or false
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': set this to true or false
  es5-ext: set this to true or false
  prisma: true
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
